import type { INodeProperties } from 'n8n-workflow';
import { pingFields, pingOptions } from './measurements/pingDescription';
import { tracerouteFields, tracerouteOptions } from './measurements/tracerouteDescription';
import { dnsFields, dnsOptions } from './measurements/dnsDescription';
import { mtrFields, mtrOptions } from './measurements/mtrDescription';
import { httpFields, httpOptions } from './measurements/httpDescription';

const operations: string[] = [
	'measurementPing',
	'measurementTraceroute',
	'measurementDns',
	'measurementMtr',
	'measurementHttp',
];

export const measurementsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['measurements'],
			},
		},
		options: [...pingOptions, ...tracerouteOptions, ...dnsOptions, ...mtrOptions, ...httpOptions],
		default: '',
	},
];

export const measurementsFields: INodeProperties[] = [
	{
		displayName: 'Target',
		name: 'measurementTarget',
		type: 'string',
		default: '',
		required: true,
		description:
			'A publicly reachable measurement target. Typically a hostname, an IPv4 address, or IPv6 address, depending on the measurement type. Support for IPv6 targets is currently considered experimental.',
		displayOptions: {
			show: {
				resource: ['measurements'],
				operation: operations,
			},
		},
	},
	// location
	{
		displayName: 'Locations',
		name: 'measurementLocationsUi',
		placeholder: 'Add location',
		type: 'fixedCollection',
		default: {},
		typeOptions: {
			multipleValues: true,
		},
		displayOptions: {
			show: {
				resource: ['measurements'],
				operation: operations,
			},
		},
		options: [
			{
				name: 'measurementLocations',
				displayName: 'Locations',
				values: [
					{
						displayName: 'Continent',
						name: 'continent',
						type: 'options',
						description: 'A two-letter continent code',
						options: [
							{
								name: '[Not Specified]', //added brackets to skip node-param-collection-type-unsorted-items rule about alphabetical order if more than 5 items
								value: 'null',
							},
							{
								name: 'Africa',
								value: 'AF',
							},
							{
								name: 'Antarctica',
								value: 'AN',
							},
							{
								name: 'Asia',
								value: 'AS',
							},
							{
								name: 'Europe',
								value: 'EU',
							},
							{
								name: 'North America',
								value: 'NA',
							},
							{
								name: 'Oceania',
								value: 'OC',
							},
							{
								name: 'South America',
								value: 'SA',
							},
						],
						default: 'null',
					},
					{
						displayName: 'Region',
						name: 'region',
						type: 'options',
						description:
							'A geographic region name based on UN Standard Country or Area Codes for Statistical Use (M49)',
						options: [
							{
								name: '[Not Specified]',
								value: 'null',
							},
							{
								name: 'Australia and New Zealand',
								value: 'Australia and New Zealand',
							},
							{
								name: 'Caribbean',
								value: 'Caribbean',
							},
							{
								name: 'Central America',
								value: 'Central America',
							},
							{
								name: 'Central Asia',
								value: 'Central Asia',
							},
							{
								name: 'Eastern Africa',
								value: 'Eastern Africa',
							},
							{
								name: 'Eastern Asia',
								value: 'Eastern Asia',
							},
							{
								name: 'Eastern Europe',
								value: 'Eastern Europe',
							},
							{
								name: 'Melanesia',
								value: 'Melanesia',
							},
							{
								name: 'Micronesia',
								value: 'Micronesia',
							},
							{
								name: 'Middle Africa',
								value: 'Middle Africa',
							},
							{
								name: 'Northern Africa',
								value: 'Northern Africa',
							},
							{
								name: 'Northern America',
								value: 'Northern America',
							},
							{
								name: 'Northern Europe',
								value: 'Northern Europe',
							},
							{
								name: 'Polynesia',
								value: 'Polynesia',
							},
							{
								name: 'South America',
								value: 'South America',
							},
							{
								name: 'South-Eastern Asia',
								value: 'South-eastern Asia',
							},
							{
								name: 'Southern Africa',
								value: 'Southern Africa',
							},
							{
								name: 'Southern Asia',
								value: 'Southern Asia',
							},
							{
								name: 'Southern Europe',
								value: 'Southern Europe',
							},
							{
								name: 'Western Africa',
								value: 'Western Africa',
							},
							{
								name: 'Western Asia',
								value: 'Western Asia',
							},
							{
								name: 'Western Europe',
								value: 'Western Europe',
							},
						],
						default: 'null',
					},
					{
						displayName: 'Country',
						name: 'country',
						type: 'options',
						description: 'A two-letter country code based on ISO 3166-1 alpha-2',
						options: [
							{
								name: '[Not Specified]',
								value: 'null',
							},
							{ name: 'Afghanistan', value: 'AF' },
							{ name: 'Albania', value: 'AL' },
							{ name: 'Algeria', value: 'DZ' },
							{ name: 'Andorra', value: 'AD' },
							{ name: 'Angola', value: 'AO' },
							{ name: 'Antigua and Barbuda', value: 'AG' },
							{ name: 'Argentina', value: 'AR' },
							{ name: 'Armenia', value: 'AM' },
							{ name: 'Australia', value: 'AU' },
							{ name: 'Austria', value: 'AT' },
							{ name: 'Azerbaijan', value: 'AZ' },
							{ name: 'Bahamas', value: 'BS' },
							{ name: 'Bahrain', value: 'BH' },
							{ name: 'Bangladesh', value: 'BD' },
							{ name: 'Barbados', value: 'BB' },
							{ name: 'Belarus', value: 'BY' },
							{ name: 'Belgium', value: 'BE' },
							{ name: 'Belize', value: 'BZ' },
							{ name: 'Benin', value: 'BJ' },
							{ name: 'Bhutan', value: 'BT' },
							{ name: 'Bolivia', value: 'BO' },
							{ name: 'Bosnia and Herzegovina', value: 'BA' },
							{ name: 'Botswana', value: 'BW' },
							{ name: 'Brazil', value: 'BR' },
							{ name: 'Brunei', value: 'BN' },
							{ name: 'Bulgaria', value: 'BG' },
							{ name: 'Burkina Faso', value: 'BF' },
							{ name: 'Burundi', value: 'BI' },
							{ name: 'Cabo Verde', value: 'CV' },
							{ name: 'Cambodia', value: 'KH' },
							{ name: 'Cameroon', value: 'CM' },
							{ name: 'Canada', value: 'CA' },
							{ name: 'Central African Republic', value: 'CF' },
							{ name: 'Chad', value: 'TD' },
							{ name: 'Chile', value: 'CL' },
							{ name: 'China', value: 'CN' },
							{ name: 'Colombia', value: 'CO' },
							{ name: 'Comoros', value: 'KM' },
							{ name: 'Congo (Congo-Brazzaville)', value: 'CG' },
							{ name: 'Congo (Democratic Republic)', value: 'CD' },
							{ name: 'Costa Rica', value: 'CR' },
							{ name: 'Croatia', value: 'HR' },
							{ name: 'Cuba', value: 'CU' },
							{ name: 'Cyprus', value: 'CY' },
							{ name: 'Czechia (Czech Republic)', value: 'CZ' },
							{ name: 'Denmark', value: 'DK' },
							{ name: 'Djibouti', value: 'DJ' },
							{ name: 'Dominica', value: 'DM' },
							{ name: 'Dominican Republic', value: 'DO' },
							{ name: 'Ecuador', value: 'EC' },
							{ name: 'Egypt', value: 'EG' },
							{ name: 'El Salvador', value: 'SV' },
							{ name: 'Equatorial Guinea', value: 'GQ' },
							{ name: 'Eritrea', value: 'ER' },
							{ name: 'Estonia', value: 'EE' },
							{ name: 'Eswatini (Fmr. Swaziland)', value: 'SZ' },
							{ name: 'Ethiopia', value: 'ET' },
							{ name: 'Fiji', value: 'FJ' },
							{ name: 'Finland', value: 'FI' },
							{ name: 'France', value: 'FR' },
							{ name: 'Gabon', value: 'GA' },
							{ name: 'Gambia', value: 'GM' },
							{ name: 'Georgia', value: 'GE' },
							{ name: 'Germany', value: 'DE' },
							{ name: 'Ghana', value: 'GH' },
							{ name: 'Greece', value: 'GR' },
							{ name: 'Grenada', value: 'GD' },
							{ name: 'Guatemala', value: 'GT' },
							{ name: 'Guinea', value: 'GN' },
							{ name: 'Guinea-Bissau', value: 'GW' },
							{ name: 'Guyana', value: 'GY' },
							{ name: 'Haiti', value: 'HT' },
							{ name: 'Honduras', value: 'HN' },
							{ name: 'Hungary', value: 'HU' },
							{ name: 'Iceland', value: 'IS' },
							{ name: 'India', value: 'IN' },
							{ name: 'Indonesia', value: 'ID' },
							{ name: 'Iran', value: 'IR' },
							{ name: 'Iraq', value: 'IQ' },
							{ name: 'Ireland', value: 'IE' },
							{ name: 'Israel', value: 'IL' },
							{ name: 'Italy', value: 'IT' },
							{ name: 'Jamaica', value: 'JM' },
							{ name: 'Japan', value: 'JP' },
							{ name: 'Jordan', value: 'JO' },
							{ name: 'Kazakhstan', value: 'KZ' },
							{ name: 'Kenya', value: 'KE' },
							{ name: 'Kiribati', value: 'KI' },
							{ name: 'Korea (North)', value: 'KP' },
							{ name: 'Korea (South)', value: 'KR' },
							{ name: 'Kuwait', value: 'KW' },
							{ name: 'Kyrgyzstan', value: 'KG' },
							{ name: 'Laos', value: 'LA' },
							{ name: 'Latvia', value: 'LV' },
							{ name: 'Lebanon', value: 'LB' },
							{ name: 'Lesotho', value: 'LS' },
							{ name: 'Liberia', value: 'LR' },
							{ name: 'Libya', value: 'LY' },
							{ name: 'Liechtenstein', value: 'LI' },
							{ name: 'Lithuania', value: 'LT' },
							{ name: 'Luxembourg', value: 'LU' },
							{ name: 'Madagascar', value: 'MG' },
							{ name: 'Malawi', value: 'MW' },
							{ name: 'Malaysia', value: 'MY' },
							{ name: 'Maldives', value: 'MV' },
							{ name: 'Mali', value: 'ML' },
							{ name: 'Malta', value: 'MT' },
							{ name: 'Marshall Islands', value: 'MH' },
							{ name: 'Mauritania', value: 'MR' },
							{ name: 'Mauritius', value: 'MU' },
							{ name: 'Mexico', value: 'MX' },
							{ name: 'Micronesia', value: 'FM' },
							{ name: 'Moldova', value: 'MD' },
							{ name: 'Monaco', value: 'MC' },
							{ name: 'Mongolia', value: 'MN' },
							{ name: 'Montenegro', value: 'ME' },
							{ name: 'Morocco', value: 'MA' },
							{ name: 'Mozambique', value: 'MZ' },
							{ name: 'Myanmar (Formerly Burma)', value: 'MM' },
							{ name: 'Namibia', value: 'NA' },
							{ name: 'Nauru', value: 'NR' },
							{ name: 'Nepal', value: 'NP' },
							{ name: 'Netherlands', value: 'NL' },
							{ name: 'New Zealand', value: 'NZ' },
							{ name: 'Nicaragua', value: 'NI' },
							{ name: 'Niger', value: 'NE' },
							{ name: 'Nigeria', value: 'NG' },
							{ name: 'North Macedonia', value: 'MK' },
							{ name: 'Norway', value: 'NO' },
							{ name: 'Oman', value: 'OM' },
							{ name: 'Pakistan', value: 'PK' },
							{ name: 'Palau', value: 'PW' },
							{ name: 'Panama', value: 'PA' },
							{ name: 'Papua New Guinea', value: 'PG' },
							{ name: 'Paraguay', value: 'PY' },
							{ name: 'Peru', value: 'PE' },
							{ name: 'Philippines', value: 'PH' },
							{ name: 'Poland', value: 'PL' },
							{ name: 'Portugal', value: 'PT' },
						],
						default: 'null',
					},
					{
						displayName: 'State',
						name: 'state',
						type: 'options',
						description: 'A two-letter US state code',
						options: [
							{
								name: '[Not Specified]',
								value: 'null',
							},
							{ name: 'Alabama', value: 'AL' },
							{ name: 'Alaska', value: 'AK' },
							{ name: 'American Samoa', value: 'AS' },
							{ name: 'Arizona', value: 'AZ' },
							{ name: 'Arkansas', value: 'AR' },
							{ name: 'California', value: 'CA' },
							{ name: 'Colorado', value: 'CO' },
							{ name: 'Connecticut', value: 'CT' },
							{ name: 'Delaware', value: 'DE' },
							{ name: 'District of Columbia', value: 'DC' },
							{ name: 'Florida', value: 'FL' },
							{ name: 'Georgia', value: 'GA' },
							{ name: 'Guam', value: 'GU' },
							{ name: 'Hawaii', value: 'HI' },
							{ name: 'Idaho', value: 'ID' },
							{ name: 'Illinois', value: 'IL' },
							{ name: 'Indiana', value: 'IN' },
							{ name: 'Iowa', value: 'IA' },
							{ name: 'Kansas', value: 'KS' },
							{ name: 'Kentucky', value: 'KY' },
							{ name: 'Louisiana', value: 'LA' },
							{ name: 'Maine', value: 'ME' },
							{ name: 'Maryland', value: 'MD' },
							{ name: 'Massachusetts', value: 'MA' },
							{ name: 'Michigan', value: 'MI' },
							{ name: 'Minnesota', value: 'MN' },
							{ name: 'Mississippi', value: 'MS' },
							{ name: 'Missouri', value: 'MO' },
							{ name: 'Montana', value: 'MT' },
							{ name: 'Nebraska', value: 'NE' },
							{ name: 'Nevada', value: 'NV' },
							{ name: 'New Hampshire', value: 'NH' },
							{ name: 'New Jersey', value: 'NJ' },
							{ name: 'New Mexico', value: 'NM' },
							{ name: 'New York', value: 'NY' },
							{ name: 'North Carolina', value: 'NC' },
							{ name: 'North Dakota', value: 'ND' },
							{ name: 'Northern Mariana Islands', value: 'MP' },
							{ name: 'Ohio', value: 'OH' },
							{ name: 'Oklahoma', value: 'OK' },
							{ name: 'Oregon', value: 'OR' },
							{ name: 'Pennsylvania', value: 'PA' },
							{ name: 'Puerto Rico', value: 'PR' },
							{ name: 'Rhode Island', value: 'RI' },
							{ name: 'South Carolina', value: 'SC' },
							{ name: 'South Dakota', value: 'SD' },
							{ name: 'Tennessee', value: 'TN' },
							{ name: 'Texas', value: 'TX' },
							{ name: 'Trust Territories', value: 'TT' },
							{ name: 'Utah', value: 'UT' },
							{ name: 'Vermont', value: 'VT' },
							{ name: 'Virgin Islands', value: 'VI' },
							{ name: 'Virginia', value: 'VA' },
							{ name: 'Washington', value: 'WA' },
							{ name: 'West Virginia', value: 'WV' },
							{ name: 'Wisconsin', value: 'WI' },
							{ name: 'Wyoming', value: 'WY' },
						],
						default: 'null',
					},
					{
						displayName: 'City',
						name: 'city',
						type: 'string',
						description: 'A city name in English',
						default: '',
					},
					{
						displayName: 'ASN',
						name: 'asn',
						type: 'number',
						description: 'An autonomous system number (ASN)',
						default: '',
					},
					{
						displayName: 'Network',
						name: 'network',
						type: 'string',
						description: 'A network name, such as "Google LLC" or "DigitalOcean, LLC"',
						default: '',
					},
					{
						displayName: 'Tags',
						name: 'tagsUi',
						placeholder: 'Add tag',
						type: 'fixedCollection',
						typeOptions: {
							multipleValues: true,
						},
						description:
							'An array of additional values to fine-tune probe selection:\n' +
							'\n' +
							'1. Probes hosted in AWS and Google Cloud are automatically assigned the service region code. For example: aws-eu-west-1 and gcp-us-south1.\n' +
							'2. Probes are automatically assigned datacenter-network and eyeball-network tags to distinguish between datacenter and end-user locations.',
						options: [
							{
								name: 'tags',
								displayName: 'Tags',
								values: [
									{
										displayName: 'Tag',
										name: 'tag',
										type: 'string',
										default: '',
									},
								],
							},
						],
						default: {},
					},
					{
						displayName: 'Magic',
						name: 'magic',
						type: 'string',
						description:
							'Locations defined in a single string instead of the respective location properties. The API performs fuzzy matching on the country, city, state, continent, region, asn (using AS prefix, e.g., AS123), tags, and network values. Supports full names, ISO codes (where applicable), and common aliases. Multiple conditions can be combined using the + character, which behaves like a logical AND',
						default: '',
					},
					{
						displayName: 'Limit',
						name: 'limit',
						type: 'number',
						description: 'Max number of results to return',
						default: 50,
						typeOptions: {
							minValue: 1,
						},
					},
				],
			},
		],
	},
	{
		displayName: 'Limit',
		name: 'measurementLimit',
		type: 'number',
		description:
			"The maximum number of probes that should run the measurement. The result count might be lower if there aren't enough probes available in the specified locations. Mutually exclusive with the limit property that can be set for individual locations.\n" +
			'\n' +
			'Constraints: Min 1┃Max 500 Default: 1',
		default: 1,
		typeOptions: {
			maxValue: 500,
			minValue: 1,
		},
	},
	{
		displayName: 'Attempts',
		name: 'attempts',
		type: 'number',
		default: 5,
		required: true,
		description: 'The maximum number of requests required to retrieve a measurement',
		displayOptions: {
			show: {
				resource: ['measurements'],
				operation: operations,
			},
		},
	},
	{
		displayName: 'Timeout',
		name: 'timeout',
		type: 'number',
		default: 1,
		required: true,
		description: 'Timeout duration (in seconds) between attempts',
		displayOptions: {
			show: {
				resource: ['measurements'],
				operation: operations,
			},
		},
	},
	...pingFields,
	...tracerouteFields,
	...dnsFields,
	...mtrFields,
	...httpFields,
];
