# workflow for test and lint every commit pushed
name: Test and lint
on:
  push:

jobs:
  test:
    name: test_and_lint
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - name: Check out commit
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          pnpm i

      - name: Lint
        run: |
          pnpm lint
